sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: "root"
    password: "060723"
  local-upload:
    base-path: D:/ProgramFiles/CodeProjects/PeakSend/uploads
  wechat:
    appid: "wxbfdcbbe6d7823895"
    secret: "df96866efe9a6fce7e62a56633818b95"
    pay-mode: "mock"
  cache:
    default-ttl: 30m
    category-ttl: 20m
    dish-ttl: 30m
    setmeal-ttl: 35m
    address-book-by-id-ttl: 2m
    report-ttl: 5m

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: "060723"
    database: 0
