sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: "root"
    password: "060723"
  local-upload:
    base-path: D:/ProgramFiles/CodeProjects/PeakSend/uploads
  wechat:
    appid: "wxbfdcbbe6d7823895"
    secret: "5ec99546047003357bc77e328cf9cf00"

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: "060723"
    database: 0
