server:
  port: 8083

spring:
  application:
    name: product-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  cloud:
    nacos:
      discovery:
        enabled: ${SKY_NACOS_DISCOVERY_ENABLED:false}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    level: "traceId=%X{traceId} %5p"
  level:
    com:
      sky:
        product:
          mapper: debug
          service: info
          controller: info

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${DB_HOST:127.0.0.1}
    port: ${DB_PORT:3306}
    database: ${DB_NAME:sky_take_out}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:060723}
